### ISSUE TITLE
`adduser` lacks `--uid`, `addgroup` lacks `--gid`

### ISSUE THREAD

**Issue by Coachonko** [ammnt/freenginx#2]
There are necessary to allow freenginx to access bind-mounted directories.
The host needs to know the uid and gid to `chown` the mounted directories.

**Comment by ammnt** [comment]
Hi! Okay it has been added now:
https://github.com/ammnt/freenginx/commit/dd3f19b67c660e5f6f97806130ba4ff4890dd0e4

**Comment by Coachonko** [comment]
Thank you, now I can use your image
